### PR TITLE
fix: Issue with Korean Input: Loss of TextEditingRange When Alternating Consonant and Vowel

### PR DESCRIPTION
**Pull request by kyungilcho**
#755 

Previously, when Korean is editing, composing is not working correctly. composing region changed by the framework.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@kyungilcho On which platform did you test it?

**Comment by kyungilcho** [comment]
It was Android, Galaxy S7 tablet and Galaxy S20 smart phone.

**Comment by kyungilcho** [comment]
I have tried many different platforms(iOS tablet, iOS(17.x)) and I have faced same issue. Now I fixed the issue please test it and give me feed back.

**Comment by LucasXu0** [comment]
The latest version 3.0.0 should include the fix for the text range composition issue.

**Pull request closed without merging**
