### PR TITLE
fix: scroll to heading is too slow (#2952)

### PR DESCRIPTION
**Pull request by johansutrisno**
Linked to [#2952](https://github.com/AppFlowy-IO/AppFlowy/issues/2952)

[Bug] The animation of scrolling to heading is too slowly when using outline

### CODE REVIEW

**Review by Xazin — APPROVED** [review]

**Comment by Xazin** [comment]
Hey @johansutrisno, can you rebase when you have time? I'll take a look after and make sure to merge if there are no problems. :+1:

**Comment by johansutrisno** [comment]
@Xazin after I rebase, I think the issue has been resolved, so should this PR be closed without needing to be merged?

**Comment by Xazin** [comment]
> @Xazin after I rebase, I think the issue has been resolved, so should this PR be closed without needing to be merged?

I will check it out.

**Comment by LucasXu0** [comment]
I picked this commit to another PR and merged it. So this bug has been fixed and will close this PR.

**Pull request closed without merging**
