### PR TITLE
fix:chinese input 610

### PR DESCRIPTION
**Pull request by q200892907**
#610  test window/linux @LucasXu0

### CODE REVIEW

**Comment by LucasXu0** [comment]
Have you tested it on Windows?

**Comment by q200892907** [comment]
> Have you tested it on Windows?


I have tested on Windows and it can be used, but the test is not comprehensive enough.

**Comment by q200892907** [comment]
I don’t know what problem the Windows judgment added at that time was used to solve. You can do a test based on the problem at that time.

**Comment by q200892907** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/73ca0858-565a-4358-8e04-91ac524fee8e

windows test video

**Comment by LucasXu0** [comment]
@q200892907 Thanks for contributing.

**Pull request merged**
