### PR TITLE
feat: improve mobile selection

### PR DESCRIPTION
**Pull request by richardshiue**
|Interaction| Android | iOS |
|:---:| :---:|:---:|
| tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/33f9beec-d20c-40f7-b55c-4368fa22c308"> |<video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/b6d5f473-6c9a-4861-a206-fd5991039acd">|
| double tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/62186fd7-ed77-4c96-9350-44d66961fed6"> | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/1f640fcf-3c15-4b67-a5b6-8cdea26407e8">|
| triple tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/d49c95c1-1cdc-41ee-88b4-fd82a15129a8"> | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/b0215a82-1b6a-47a3-893b-6d4ed98b2d27"> |
| long press + pan | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/b54830b1-e694-4222-88a2-4a8572059a44"> | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/4a992d0b-98b4-4705-bfcb-7b54e35adef0"> |
| regular pan | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/3666d847-62b8-4a01-a9a6-54733bfc532c"> | N/A |

### CODE REVIEW

**Review by richardshiue — COMMENTED** [review]
Is it absolutely necessary to use `updateSelection`? Will a `editorState.updateSelectionWithReason` be good enough?

**Review by richardshiue — COMMENTED** [review]
I don't see the collapsed handler on main or here, but I don't know why?

**Comment by LucasXu0** [comment]
> Is it absolutely necessary to use updateSelection? Will a editorState.updateSelectionWithReason be good enough?

Using editorState.selection or editorState.updateSelectionWithReason are both OK.

> I don't see the collapsed handle for iOS on main or here, but I don't know why?

In most cases, iOS does not feature a collapsed handle. iOS users can update a collapsed selection by long-pressing on it.

@richardshiue By the way, the word count service test failed.

**Comment by richardshiue** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/pull/771 introduced a change to the word counting regex. `AppFlowy!AppFlowy` should be counted as two words, not one. @Xazin I think this is a regression.

**Pull request merged**
