### PR TITLE
fix: make positioning of LinkMenu dependent on position of selection

### PR DESCRIPTION
**Pull request by lxndrsldtv**
Proposal of fix for the issue "Link Dialog is partially invisible at the bottom of the page", reported to AppFlowy 

https://github.com/AppFlowy-IO/AppFlowy/issues/2322

initial behaviour:

https://user-images.githubusercontent.com/18658711/234530262-f2280cb0-5279-477e-bd58-9d3b0b9e2897.mov

behaviour with applied changes:

https://user-images.githubusercontent.com/18658711/234531418-3032b6d3-f508-4e97-9efb-940225931815.mov

### CODE REVIEW

**Comment by lxndrsldtv** [comment]
I'll fix that ⬆️

**Comment by MayurSMahajan** [comment]
Hey @lxndrsldtv ! Thank you for submitting a PR. I request you to take a look at these commit message [guidelines](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/code-submission-guidelines#commit-message-guidelines): 

Also if you can write some tests relating to your PR, that would solve the codecov check as well. 
Thanks again!

**Comment by MayurSMahajan** [comment]
@lxndrsldtv Let me know if you need help for writing tests.

**Comment by lxndrsldtv** [comment]
@MayurSMahajan, thanks, I'll let you know. 
For now trying to figure out how to check the functionality with widget tests. 🤔

**Comment by MayurSMahajan** [comment]
@lxndrsldtv Take your time, hit me on discord if you need something.

**Comment by lxndrsldtv** [comment]
Hi!
I've added widget test to code changes.
I'm not sure, that the test is in right place, now it is at file toolbar_rich_text_test.dart. If there is better place please advice it.
And, maybe, it will be better to make new PR instead this one?

**Review by MayurSMahajan — CHANGES_REQUESTED** [review]
Hey @lxndrsldtv, great work! You should put the test in the same folder structure as the file you are testing. So in your case, it should be `test/render/toolbar/toolbar_item_test.dart`.

**Comment by MayurSMahajan** [comment]
No need to create a new PR, the tests will solve the CodeCov check and the Commit Message Lint check can be waived by one of our maintainers.

**Comment by lxndrsldtv** [comment]
@MayurSMahajan ok, thanks, I'll move the test at new place, as you suggested.

**Review by MayurSMahajan — APPROVED** [review]
Seems alright to me!

**Pull request closed without merging**
