### PR TITLE
fix: allow active toolbar widget colour to be customised

### PR DESCRIPTION
**Pull request by garv-shah**
While trying to customise the editor, I noticed that the colour for the selected toolbar button was hard-coded to `Colors.lightBlue`, resulting in the following output:
SCR-20230629-kxxq

This didn't match the accent colour for my app, so I added `toolbarActiveColor` as a property on EditorStyle which allows this to be customised 👍

### CODE REVIEW

**Comment by LucasXu0** [comment]
@garv-shah The CI failed. Please format the code.

**Comment by garv-shah** [comment]
@LucasXu0 Hi Lucas! I've reformatted the PR to to pass the GitHub tests, but I'm unsure of what to do to increase the coverage of my diff in order to pass the codecov test. Would you please be able to give me a bit of guidance on what kind of tests I would have to implement?

**Comment by LucasXu0** [comment]
Hey, @garv-shah. I think adding the toolbar active color is not a good way because the toolbar isn't a part of the editor; it's more like an extension or plugin for the editor. I suggest moving this logic to the toolbar itself.

**Comment by garv-shah** [comment]
Alright, can do! I'll try to add it as a property to both `FloatingToolbar` and `MobileToolbar` 👍

**Comment by LucasXu0** [comment]
@garv-shah Are you still working on it? If not, I will refactor this part.

**Comment by garv-shah** [comment]
Hi Lucas! Ah, sorry, completely forgot about it in the midst of other work. I'll try to fix it up now

**Comment by LucasXu0** [comment]
@garv-shah Never mind. Just let me know if you need any help.

**Comment by garv-shah** [comment]
@LucasXu0 All done! I currently can't build my app for iOS because of [this](https://github.com/AppFlowy-IO/AppFlowy/issues/2934) issue, so I can't check if it works on mobile as well, but this should be all good for desktop 👍 
Thanks!

**Comment by LucasXu0** [comment]
> @LucasXu0 All done! I currently can't build my app for iOS because of [this](https://github.com/AppFlowy-IO/AppFlowy/issues/2934) issue, so I can't check if it works on mobile as well, but this should be all good for desktop 👍 Thanks!

The toolbar on the mobile platform doesn't using the floating toolbar since they're with totally different behavior and style. The editor can run perfectly on mobile devices.

**Comment by LucasXu0** [comment]
FYI, @garv-shah. I added a test for customizing the toolbar active color. https://github.com/AppFlowy-IO/appflowy-editor/pull/261/commits/4f41e763ebebebcd8482ec4d5a03f1e7c0616ab8

**Pull request merged**
