### PR TITLE
fix: add support for breakline and divider

### PR DESCRIPTION
**Pull request by penkzhou**
1. current convert method `documentToHTML` will transfer the empty line into empty `p` tag. This will make when render the markdown content into html ignore the  empty `p` tag which will ignore all the break lines.
2. add support for the `divider` tag. it will transfer `divider` into `hr` tag.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@penkzhou Please include the tests.

**Comment by penkzhou** [comment]
@LucasXu0 just add the test for <br> tag.

**Comment by LucasXu0** [comment]
@penkzhou There're two tests failed.

**Comment by penkzhou** [comment]
get. need some modify.

**Pull request merged**
