### PR TITLE
fix: #202

### PR DESCRIPTION
**Pull request by liyaowhen**
adds ability to remove text highlight and color by adding a default option for both menus

### CODE REVIEW

**Comment by liyaowhen** [comment]
i closed the #203 because I used the wrong account :(

**Comment by LucasXu0** [comment]
The default background color should be `Colors.transparent` instead of `Colors.white`.

**Comment by LucasXu0** [comment]
And the default text color should be same as the text color from `TextStyleConfiguration`

**Comment by liyaowhen** [comment]
ok, ill make another pull request when I fix it :)

**Comment by liyaowhen** [comment]
oh, i just realized i can add more to the pull request :)

**Comment by liyaowhen** [comment]
nevernmind, my build setup is broken.

**Pull request closed without merging**
