### PR TITLE
fix: export pdf set font not work

### PR DESCRIPTION
**Pull request by Linij**
fix issue: https://github.com/AppFlowy-IO/appflowy-editor/issues/922

### CODE REVIEW

**Comment by Xazin** [comment]
Seems the formatter is complaining about the pdf to html file not being formatted. 🙏

**Comment by Linij** [comment]
> Seems the formatter is complaining about the pdf to html file not being formatted. 🙏
You look like you haven't used exporting pdf.
Go Look #922

**Comment by Xazin** [comment]
> > Seems the formatter is complaining about the pdf to html file not being formatted. 🙏
> > You look like you haven't used exporting pdf.
> > Go Look #922

I don't understand what you're saying?

The pipeline is complaining that you didn't format a file correctly.

image

image

**Comment by Linij** [comment]
> > > Seems the formatter is complaining about the pdf to html file not being formatted. 🙏
> > > You look like you haven't used exporting pdf.
> > > Go Look #922
> 
> I don't understand what you're saying?
> 
> The pipeline is complaining that you didn't format a file correctly.
> 
> image
> 
> image

I misunderstood, sorry, my translation software translated you say, "I am a formatting complainant, and only formatting is in the submission"

**Review by LucasXu0 — APPROVED** [review]

**Pull request merged**
