### PR TITLE
fix: editor now detects phone number and launches it

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
### Description
This PR addresses **Issue #957**, ensuring that phone numbers are detected, highlighted, and functional within the AppFlowy Editor. The issue has been resolved, and this PR closes it.

---

### Key Improvements
- **Phone Number Detection**: Phone numbers are now automatically detected and highlighted, following the same style as URLs.
- **Interactive Features**:
  - On mobile devices, tapping a phone number allows users to:
    - Call the number.
    - Save it to their contacts directory.
- **Non-Intrusive Changes**:
  - Existing functionalities for URLs and emails remain unaffected.
  - All code follows established formatting guidelines and includes comments for clarity.

---

### Testing Details
- **Test Results**:
  - All existing and new test cases pass successfully.
  - Comprehensive manual testing was conducted to verify functionality across supported platforms.
 
- **Test Screenshots**:
    Test Screenshot 1

    Test Screenshot 2

- **Demonstration**:
  - Here’s a video showcasing the functionality on an Android 15 emulator:
    [Video Demonstration](https://github.com/user-attachments/assets/fa052d94-ccbb-487d-8b50-48b0f44dad78)

---

### How to Test
1. Copy paste a phone number in the editor.
2. Verify that:
   - The phone number is highlighted in the same way as URLs and emails.
   - Tapping the phone number on a mobile device triggers the appropriate action (call/save).
3. Confirm that URLs and emails continue to function as expected.

---

### Additional Notes
- **Code Standards**: The implementation follows the project's code style guidelines and includes inline comments for better maintainability.
- **Backward Compatibility**: No existing functionalities have been disturbed by this update.

Please let me know if additional modifications or improvements are required!

### CODE REVIEW

**Comment by LucasXu0** [comment]
@ARYPROGRAMMER Can you add a test for the paste_command?

**Comment by ARYPROGRAMMER** [comment]
> @ARYPROGRAMMER Can you add a test for the paste_command?

Hey, can I add a comprehensive test in another PR after this gets merged, would make it cleaner and more effective instead of adding all in one.

**Comment by ARYPROGRAMMER** [comment]
> > @ARYPROGRAMMER Can you add a test for the paste_command?
> 
> Hey, can I add a comprehensive test in another PR after this gets merged, would make it cleaner and more effective instead of adding all in one.

> @ARYPROGRAMMER Can you add a test for the paste_command?

added required tests as tests were specific to the added feat and can be covered easily, new coverage: 69.47%

**Comment by ARYPROGRAMMER** [comment]
@LucasXu0 please review and merge

**Comment by LucasXu0** [comment]
I triggered the CI jobs and will merge the PR after all of them pass.

**Comment by ARYPROGRAMMER** [comment]
> I triggered the CI jobs and will merge the PR after all of them pass.

let me quickly fix these lints

**Comment by ARYPROGRAMMER** [comment]
> I triggered the CI jobs and will merge the PR after all of them pass.

just the commit message lint ci shows error since i pushed "added tests..." commit which is not of expected type , rest everything passes

**Comment by ARYPROGRAMMER** [comment]
@LucasXu0 I tried changing commit name via amend, it didn't work, i think this ci would not affect much

**Comment by ARYPROGRAMMER** [comment]
@LucasXu0 any updates on this?

**Comment by LucasXu0** [comment]
@ARYPROGRAMMER I can squash the PR. Thanks.

**Pull request merged**
