### PR TITLE
feat: table html encoder and decoder added

### PR DESCRIPTION
**Pull request by alihassan143**
#426

### CODE REVIEW

**Comment by alihassan143** [comment]
@LucasXu0 pr is ready for review

**Comment by LucasXu0** [comment]
Hey, @alihassan143. You've made changes to all the files once more. Kindly modify only the necessary files or submit another pull request to format the code.

**Comment by alihassan143** [comment]
@LucasXu0  i am using the latest flutter sdk it automatically added unecessary quotes when i ran dart --fix-apply

**Comment by alihassan143** [comment]
@LucasXu0  i will create another pr

**Pull request closed without merging**
