### PR TITLE
feat: support auto scroll after selection updated

### PR DESCRIPTION
**Pull request by LucasXu0**

### CODE REVIEW

**Comment by LucasXu0** [comment]
Hey, @alihassan143. I implemented the auto scroll feature when users update the cursor position by tapping or arrow keys. Is it the feature you want to implement?

I moved the scroller logic from selection service to scroll service.  


https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/4f1b2b6a-7494-4d8f-9192-3b9cef846c55

**Comment by alihassan143** [comment]
@LucasXu0  let me check yes i want the same thing

**Comment by LucasXu0** [comment]
@alihassan143 I was trying to update your PR. However, I don't know why there're differences between desktop and mobile.

```dart
@override
  void scrollOnUpdate(
    EditorState editorState, {
    Rect? cursorRect,
    BuildContext? context,
    List<Node>? currentSelectedNodes,
    Selection? currentSelection,
  }) {
    if (Platform.isAndroid || Platform.isIOS) {
        // ...
    } else {
        // ...
    }
}
```

**Comment by LucasXu0** [comment]
My idea is to add a selection listener to the scroll selection. Then, when there's an update to the selection, fetching the rect of the selection and passing it to the scroller, let the scroller decide whether or not to scroll automatically.

**Comment by alihassan143** [comment]
@LucasXu0  no issue i will close my pr

**Pull request merged**
