### PR TITLE
Fix: Bug - arrow problem 4764

### PR DESCRIPTION
**Pull request by Taverz**
This problem is related to the paragraph, since after the paragraph there is no line it has nowhere to go.I made it so that even within a paragraph you can move between lines. I did this so that you can disable this feature, and also fixed some things in the code.
https://github.com/AppFlowy-IO/AppFlowy/issues/4764

### CODE REVIEW

**Comment by Taverz** [comment]
Oops, it seems I did something wrong, I would like to fix it and restart))
How to run Github Action for checks?

**Comment by LucasXu0** [comment]
Hi, @Taverz. You can run these commands locally.

```shell
  flutter --version
  flutter pub get
  flutter analyze .
  dart format --set-exit-if-changed .
  flutter test --coverage
```

**Comment by Taverz** [comment]
Hi, @LucasXu0 .
What to do after I ran these commands and checked everything, what exactly do I need to do, I don’t know how to do it correctly. Tell me please

**Comment by LucasXu0** [comment]
@Taverz If all the tests and analyses are passed, then the GitHub CI won't complain.

**Pull request closed without merging**
