### PR TITLE
build error fixed which was happening due to Node Visitor

### PR DESCRIPTION
**Pull request by rnp0728**
issue #678 fixed

### CODE REVIEW

**Comment by rnp0728** [comment]
Signed the CLA, recheck it.

**Comment by Xazin** [comment]
> Signed the CLA, recheck it.

Hey, about the CLA, it should be instant, can you try again?

**Comment by rnp0728** [comment]
@Xazin can you please explain me why the tests failed?

**Comment by Xazin** [comment]
> @Xazin can you please explain me why the tests failed?

The tests didn't fail, upload to codecov failed, it's a step that we have no control over, and it sometimes is a bit flaky.

As you haven't signed the CLA yet, I'll close this one in favor of another PR.

**Comment by rnp0728** [comment]
@Xazin thanks for raising a new PR.

**Pull request closed without merging**
