### PR TITLE
Upload images from local files 

### PR DESCRIPTION
**Pull request by Mukund-Tandon**
fixes: #200 

https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/2bf78fdd-b66d-4728-89fc-1099400cd7c2

### CODE REVIEW

**Comment by LucasXu0** [comment]
Hey, @Mukund-Tandon Any updates?

**Comment by Mukund-Tandon** [comment]
> Hey, @Mukund-Tandon Any updates?

I am working on it will sumbit a changes by tommorow, sorry for the delay
Screenshot 2023-06-26 at 2 37 45 PM

**Comment by LucasXu0** [comment]
@Mukund-Tandon Okay, just let me know if you need any help.

**Comment by Mukund-Tandon** [comment]
@LucasXu0 , please can you review this , I have made the UI changes and also handled the case where if the image is not found at its source it should display error. I am working on writing test for these.

https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/c73cd2ea-db2c-4745-a40c-1eb934fd1e32

**Comment by LucasXu0** [comment]
Nice, I will check it out. Also, I plan to modify something on your branch.

**Comment by LucasXu0** [comment]
Suddenly, I have another idea to solve the deleted image problem. I plan to save the image value as base64, then we don't need to handle the error anymore.

Let me do that on your branch.

**Comment by LucasXu0** [comment]
FYI, @Mukund-Tandon. I have submitted the code. Please check them. 

By the way, please rebase or merge the main branch as the pull request conflicts with it.

**Comment by Mukund-Tandon** [comment]
> FYI, @Mukund-Tandon. I have submitted the code. Please check them.
> 
> By the way, please rebase or merge the main branch as the pull request conflicts with it.

Ok, I have updated my branch to resolve the merge conflicts .I will be now fixing some failing tests and will add more.

**Comment by LucasXu0** [comment]
@Mukund-Tandon Have you updated the branch? I didn't see any new commits.

**Comment by Mukund-Tandon** [comment]
> @Mukund-Tandon Have you updated the branch? I didn't see any new commits.
Just pushed the changes 😅

**Comment by Mukund-Tandon** [comment]
@LucasXu0  ,I had a doubt, what is the use of the files under image(location - lib/src/render/image
Screenshot 2023-06-28 at 12 05 53 PM

**Comment by LucasXu0** [comment]
@Mukund-Tandon They're deprecated.

Are you working on fixing the tests? If not, I can do that.

**Comment by Mukund-Tandon** [comment]
> @Mukund-Tandon They're deprecated.
> 
> Are you working on fixing the tests? If not, I can do that.

Yes I working on the test, actually the tests of these files where only remaining failing test , so should I delete the test file of under image?

**Comment by LucasXu0** [comment]
No worries. Let me fix them.

**Comment by Mukund-Tandon** [comment]
> No worries. Let me fix them.

Ok, so now should I proceed to work on other issues?

**Comment by LucasXu0** [comment]
> > No worries. Let me fix them.
> 
> Ok, so now should I proceed to work on other issues?

Yep. Just choose the issues you want to solve.

**Comment by Davidzhu001** [comment]
does it has a callback so i can upload image

**Comment by Mukund-Tandon** [comment]
> does it has a callback so i can upload image

Hi, I don't completely understand your question, but we can upload an image from our local device as well as paste an image URL.

https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/1a2d68c1-36d9-488a-9328-02293ba4747b

Is there anything I am missing?

**Comment by Davidzhu001** [comment]
i can see the local image url, I am thinking if the user choose a image. i can get the event and upload the image to my server.

**Comment by D3vcode88** [comment]
Bonjour le téléversement d'image sur la version 0.6.9 d'appflowy ne fonctionne pas, est-ce que c'est du à un bug ?

**Comment by D3vcode88** [comment]
Hello, the image upload on appflowy version 0.6.9 doesn't work, is it due to a bug? If it's not active yet, when will it be?
Is there an image integration service on appflowy, until this feature is available?

**Pull request merged**
